// Writes src/html/convert/entity_tree.rs: the decode trie of the npm package `entities`,
// which htmlparser2 walks to decode named character references.
//
//   node crates/icloud-mail/tests/fixtures/html/entity_tree.mjs
//
// REPOSITORY is the checkout whose node_modules holds html-to-text 10.0.1: the
// directory the script is run from, unless the variable says otherwise.
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'

const REPOSITORY = process.env.REPOSITORY ?? process.cwd()

// `entities` as htmlparser2 resolves it, not as the repository root does.
const fromHtmlToText = createRequire(
  `${REPOSITORY}/node_modules/.pnpm/html-to-text@10.0.1/node_modules/html-to-text/lib/html-to-text.mjs`
)
const fromHtmlparser2 = createRequire(fromHtmlToText.resolve('htmlparser2'))
const { htmlDecodeTree } = fromHtmlparser2('entities/decode')
// The package does not export its package.json: read it next to the module it does export.
const decodePath = fromHtmlparser2.resolve('entities/decode')
const packagePath = decodePath.slice(0, decodePath.lastIndexOf('/dist/')) + '/package.json'
const { version } = JSON.parse(readFileSync(packagePath, 'utf8'))

const rows = []
for (let index = 0; index < htmlDecodeTree.length; index += 12) {
  rows.push('    ' + Array.from(htmlDecodeTree.slice(index, index + 12)).join(', ') + ',')
}

const source = `//! Generated by \`tests/fixtures/entity_tree.mjs\` from \`entities\` ${version}. Do not edit.

/// \`htmlDecodeTree\` of \`entities/decode\`: every named character reference of HTML as
/// a trie packed in 16-bit words, which \`EntityDecoder\` walks one character at a time.
#[rustfmt::skip]
pub(super) static HTML_DECODE_TREE: [u16; ${htmlDecodeTree.length}] = [
${rows.join('\n')}
];
`
const target = fileURLToPath(new URL('../../../src/html/convert/entity_tree.rs', import.meta.url))
writeFileSync(target, source)
console.log(`${target}: ${htmlDecodeTree.length} words`)
