/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Invites: () => import('#controllers/invites_controller'),
  Onboarding: () => import('#controllers/onboarding_controller'),
  Session: () => import('#controllers/session_controller'),
}
