/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Analytics: () => import('#controllers/analytics_controller'),
  Gateway: () => import('#controllers/gateway_controller'),
  Invites: () => import('#controllers/invites_controller'),
  Logs: () => import('#controllers/logs_controller'),
  Mcps: () => import('#controllers/mcps_controller'),
  OauthServer: () => import('#controllers/oauth_server_controller'),
  Onboarding: () => import('#controllers/onboarding_controller'),
  Session: () => import('#controllers/session_controller'),
  Settings: () => import('#controllers/settings_controller'),
}
