// Writes src/mime_types.rs from the extension table of nodemailer 10.0.14.
//
//   node crates/icloud-mail/tools/mime_types.mjs [path to node_modules/nodemailer]
//
// from the root of a checkout that has the Node version's node_modules.
//
// nodemailer keeps the table private, so it is read out of the source of
// `mime-funcs/mime-types.js`, and every entry is then checked against the
// `detectMimeType` the library exports.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const nodemailer = resolve(
  process.argv[2] ??
    'node_modules/.pnpm/nodemailer@10.0.14/node_modules/nodemailer'
)
const { version } = JSON.parse(readFileSync(join(nodemailer, 'package.json'), 'utf8'))
if (version !== '10.0.14') {
  throw new Error(`The port follows nodemailer 10.0.14, and this is ${version}`)
}

const file = join(nodemailer, 'dist/esm/mime-funcs/mime-types.js')
const source = readFileSync(file, 'utf8')
const table = /const extensions = (new Map\(\[[\s\S]*?\n\]\));/.exec(source)
if (!table) throw new Error('The extension table was not found in mime-types.js')
const extensions = new Function(`return ${table[1]}`)()

const { detectMimeType } = await import(pathToFileURL(file).href)

const entries = [...extensions]
  .map(([extension, types]) => [extension, Array.isArray(types) ? types[0] : types])
  .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))

for (const [extension, type] of entries) {
  // The lookup key is trimmed and lowercased, so any other key could never be found.
  if (extension !== extension.trim().toLowerCase() || !/^[\x21-\x7e]+$/.test(extension)) {
    throw new Error(`Unexpected extension ${JSON.stringify(extension)}`)
  }
  // The port writes these types into Content-Type as they are: each must be one
  // that nodemailer's header parser gives back unchanged.
  if (!/^[\x21-\x7e]+$/.test(type) || /[;"\\]/.test(type)) {
    throw new Error(`Unexpected media type ${JSON.stringify(type)} for ${extension}`)
  }
  if (detectMimeType(`file.${extension}`) !== type) {
    throw new Error(`nodemailer does not give ${type} for .${extension}`)
  }
}

const lines = [
  '//! The media type nodemailer 10.0.14 gives each file extension.',
  '//!',
  '//! Generated by `tools/mime_types.mjs` from `mime-funcs/mime-types.js`. Do not edit.',
  '',
  '/// Sorted by extension, for a binary search. Where nodemailer lists several',
  '/// types for an extension, this is the first, which is the one it uses.',
  '#[rustfmt::skip]',
  `pub(crate) static MEDIA_TYPES: [(&str, &str); ${entries.length}] = [`,
  ...entries.map(([extension, type]) => `    (${JSON.stringify(extension)}, ${JSON.stringify(type)}),`),
  '];',
  '',
]
writeFileSync(join(here, '../src/mime_types.rs'), lines.join('\n'))
console.log(`${entries.length} extensions written to src/mime_types.rs`)
