/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccessTokenMcpSchema extends BaseModel {
  static $columns = ['accessTokenId', 'createdAt', 'id', 'mcpId', 'updatedAt'] as const
  $columns = AccessTokenMcpSchema.$columns
  @column()
  declare accessTokenId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mcpId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AccessTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'expiresAt', 'id', 'lastUsedAt', 'name', 'revokedAt', 'scopeMode', 'tokenHash', 'tokenPrefix', 'updatedAt'] as const
  $columns = AccessTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare scopeMode: string
  @column()
  declare tokenHash: string
  @column()
  declare tokenPrefix: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InstanceSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'mcpLogLevel', 'mcpLogRetentionDays', 'updatedAt', 'updatedBy'] as const
  $columns = InstanceSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mcpLogLevel: string
  @column()
  declare mcpLogRetentionDays: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
}

export class InviteSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'createdBy', 'email', 'expiresAt', 'id', 'role', 'token', 'updatedAt'] as const
  $columns = InviteSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class McpCallLogSchema extends BaseModel {
  static $columns = ['accessTokenId', 'accessTokenName', 'accessTokenPrefix', 'arguments', 'argumentsCaptured', 'createdAt', 'durationMs', 'errorCategory', 'errorSummary', 'id', 'mcpId', 'mcpName', 'mcpSlug', 'outcome', 'requestedToolName', 'response', 'responseCaptured', 'toolName'] as const
  $columns = McpCallLogSchema.$columns
  @column()
  declare accessTokenId: number | null
  @column()
  declare accessTokenName: string
  @column()
  declare accessTokenPrefix: string
  @column()
  declare arguments: string | null
  @column()
  declare argumentsCaptured: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: number
  @column()
  declare errorCategory: string | null
  @column()
  declare errorSummary: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mcpId: number | null
  @column()
  declare mcpName: string | null
  @column()
  declare mcpSlug: string | null
  @column()
  declare outcome: string
  @column()
  declare requestedToolName: string
  @column()
  declare response: string | null
  @column()
  declare responseCaptured: boolean
  @column()
  declare toolName: string | null
}

export class McpSchema extends BaseModel {
  static $columns = ['authBearer', 'authHeaderName', 'authHeaderValue', 'authType', 'createdAt', 'createdBy', 'description', 'enabled', 'httpUrl', 'id', 'lastError', 'name', 'npmArgs', 'npmEnv', 'npmPackage', 'npmVersion', 'oauthAccessToken', 'oauthAuthorizeUrl', 'oauthClientAuthMethod', 'oauthClientId', 'oauthClientSecret', 'oauthIssuer', 'oauthRedirectUri', 'oauthRefreshToken', 'oauthRequired', 'oauthResource', 'oauthScopes', 'oauthTokenExpiresAt', 'oauthTokenType', 'oauthTokenUrl', 'slug', 'status', 'transport', 'updatedAt'] as const
  $columns = McpSchema.$columns
  @column()
  declare authBearer: string | null
  @column()
  declare authHeaderName: string | null
  @column()
  declare authHeaderValue: string | null
  @column()
  declare authType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare description: string | null
  @column()
  declare enabled: boolean
  @column()
  declare httpUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastError: string | null
  @column()
  declare name: string
  @column()
  declare npmArgs: string | null
  @column()
  declare npmEnv: string | null
  @column()
  declare npmPackage: string | null
  @column()
  declare npmVersion: string | null
  @column()
  declare oauthAccessToken: string | null
  @column()
  declare oauthAuthorizeUrl: string | null
  @column()
  declare oauthClientAuthMethod: string | null
  @column()
  declare oauthClientId: string | null
  @column()
  declare oauthClientSecret: string | null
  @column()
  declare oauthIssuer: string | null
  @column()
  declare oauthRedirectUri: string | null
  @column()
  declare oauthRefreshToken: string | null
  @column()
  declare oauthRequired: boolean
  @column()
  declare oauthResource: string | null
  @column()
  declare oauthScopes: string | null
  @column.dateTime()
  declare oauthTokenExpiresAt: DateTime | null
  @column()
  declare oauthTokenType: string | null
  @column()
  declare oauthTokenUrl: string | null
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare transport: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
